# Generated by Django 4.0.1 on 2022-09-27 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/propertyGallery/')),
            ],
        ),
        migrations.CreateModel(
            name='realest_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='realEstate_PropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='realEstate_Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='realEstate_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('propImage', models.BinaryField()),
                ('description', models.TextField()),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('duration', models.CharField(choices=[('/Year', '/Year'), ('/Month', '/Month'), ('/Week', '/Week'), ('/Day', '/Day'), ('/Hour', '/Hour')], max_length=20)),
                ('bedrooms', models.IntegerField()),
                ('toilets', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('location', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=20)),
                ('purpose', models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('flat', 'flat'), ('land', 'land'), ('office', 'office'), ('shop', 'shop')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imagegallery', models.ManyToManyField(to='realest.ImageAttachment')),
                ('imageuploader_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageUpload', to='auth_api.user_info_extend')),
                ('propertyType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realest.realestate_proptype')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_api.user_info_extend')),
            ],
        ),
    ]
