# Generated by Django 4.0.1 on 2022-09-27 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate_offer',
            name='propertyType',
            field=models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('flat', 'flat'), ('land', 'land'), ('office', 'office'), ('shop', 'shop')], max_length=20),
        ),
        migrations.AlterField(
            model_name='realestate_offer',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realest.realestate_proptype'),
        ),
    ]
