# Generated by Django 4.0.1 on 2022-09-27 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realest', '0002_alter_realestate_offer_propertytype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='realest_saves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='realest_application',
        ),
        migrations.RemoveField(
            model_name='realestate_offer',
            name='imagegallery',
        ),
        migrations.AddField(
            model_name='realestate_offer',
            name='imagegallery',
            field=models.FileField(blank=True, upload_to='media/propertyGallery/'),
        ),
        migrations.AlterField(
            model_name='realestate_offer',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realest.realestate_purpose'),
        ),
        migrations.DeleteModel(
            name='ImageAttachment',
        ),
        migrations.DeleteModel(
            name='realEstate_PropType',
        ),
        migrations.AddField(
            model_name='realest_saves',
            name='property_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realest.realestate_offer'),
        ),
        migrations.AddField(
            model_name='realest_saves',
            name='saver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
