# Generated by Django 4.0.1 on 2022-09-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realest', '0003_realest_saves_delete_realest_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/propertyGallery/')),
            ],
        ),
        migrations.RemoveField(
            model_name='realestate_offer',
            name='imagegallery',
        ),
        migrations.AddField(
            model_name='realestate_offer',
            name='imagegallery',
            field=models.ManyToManyField(blank=True, to='realest.ImageAttachment'),
        ),
    ]
