# Generated by Django 4.0.7 on 2022-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realest', '0004_imageattachment_remove_realestate_offer_imagegallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate_offer',
            name='propImage',
        ),
        migrations.AddField(
            model_name='realestate_offer',
            name='covered_area',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=20),
        ),
        migrations.AddField(
            model_name='realestate_offer',
            name='currency',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='realestate_offer',
            name='financing',
            field=models.CharField(default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='realestate_offer',
            name='furnished_type',
            field=models.CharField(default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='realestate_offer',
            name='instagram_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='realestate_offer',
            name='local_government',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='realestate_offer',
            name='total_area',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=20),
        ),
        migrations.AddField(
            model_name='realestate_offer',
            name='youtube_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='realestate_offer',
            name='bedrooms',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='realestate_offer',
            name='propertyType',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='realestate_offer',
            name='purpose',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
