# Generated by Django 4.0.7 on 2022-10-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realest', '0005_remove_realestate_offer_propimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate_offer',
            name='imagegallery',
        ),
        migrations.AddField(
            model_name='realestate_offer',
            name='imagegallery',
            field=models.FileField(blank=True, upload_to='media/propertyGallery/'),
        ),
    ]
