# Generated by Django 4.1 on 2022-09-05 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('yes', models.TextField(default='Yes', max_length=3)),
                ('no', models.TextField(default='No', max_length=3)),
                ('ans', models.BooleanField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_age', models.PositiveIntegerField()),
                ('child_name', models.CharField(max_length=200)),
                ('relation_to_child', models.CharField(max_length=200)),
                ('caregiver_email', models.EmailField(db_index=True, max_length=50, unique=True)),
                ('caregiver_phone', models.BigIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('caregiver_name', models.OneToOneField(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
