# Generated by Django 4.1 on 2022-09-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mchath', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='no',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='yes',
        ),
        migrations.AlterField(
            model_name='setup',
            name='caregiver_name',
            field=models.CharField(max_length=200),
        ),
    ]
