# Generated by Django 4.1 on 2022-09-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mchath', '0003_alter_setup_caregiver_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver_name', models.TextField(max_length=200)),
                ('child_age', models.PositiveIntegerField()),
                ('child_name', models.CharField(max_length=200)),
                ('relation_to_child', models.CharField(max_length=200)),
                ('caregiver_email', models.EmailField(db_index=True, max_length=50, unique=True)),
                ('caregiver_phone', models.BigIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='setup',
        ),
    ]
