# Generated by Django 4.1 on 2022-09-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mchath', '0004_customer_delete_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='caregiver_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
