# Generated by Django 4.1 on 2022-09-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mchath', '0005_alter_customer_caregiver_name_alter_customer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='op1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='op2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='caregiver_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ans',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
