# Generated by Django 4.1 on 2022-08-25 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('op1', models.BooleanField(default=False)),
                ('op2', models.BooleanField(default=False)),
                ('ans', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childage', models.PositiveIntegerField()),
                ('caregivername', models.CharField(max_length=200)),
                ('relationtochild', models.CharField(max_length=200)),
                ('caregiveremail', models.EmailField(db_index=True, max_length=50, unique=True)),
                ('caregiverphone', models.BigIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('childname', models.OneToOneField(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
