# Generated by Django 4.1 on 2022-08-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='op1',
            new_name='no',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='op2',
            new_name='yes',
        ),
        migrations.AlterField(
            model_name='test',
            name='ans',
            field=models.BooleanField(max_length=200, null=True),
        ),
    ]
