# Generated by Django 4.1 on 2022-08-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mchat', '0002_rename_op1_test_no_rename_op2_test_yes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='no',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='test',
            name='yes',
            field=models.TextField(max_length=200),
        ),
    ]
