# Generated by Django 4.1 on 2022-08-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mchat', '0003_alter_test_no_alter_test_yes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='no',
            field=models.TextField(default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='test',
            name='yes',
            field=models.TextField(default='Yes', max_length=3),
        ),
    ]
