# Generated by Django 4.1 on 2022-08-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mchat', '0005_alter_test_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='childname',
            field=models.CharField(max_length=200),
        ),
    ]
