# Generated by Django 4.1 on 2022-08-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=200)),
                ('child_age', models.PositiveIntegerField()),
                ('caregiver_name', models.CharField(max_length=200)),
                ('relation_to_child', models.CharField(max_length=200)),
                ('caregiver_email', models.EmailField(db_index=True, max_length=50, unique=True)),
                ('caregiver_phone', models.BigIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('yes', models.TextField(default='Yes', max_length=3)),
                ('no', models.TextField(default='No', max_length=3)),
                ('ans', models.BooleanField(max_length=200, null=True)),
            ],
        ),
    ]
